### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kevinresol** [abandonware/noble#109]
The following script demonstrates the leak:

```js
setInterval(() => {
	var memory = process.memoryUsage();
	console.log(new Date().toString() + ': ' + (memory.heapUsed / 1024 / 1024 * 100 | 0) / 100 + " / " + (memory.heapTotal / 1024 / 1024 * 100 | 0) / 100 + " MB");
}, 5000);
	
var noble = require("@abandonware/noble")
noble.on("discover", peripheral => {
	console.log(peripheral.id);
});
noble.on("stateChange", status => {
	if(status == "poweredOn") {
		noble.startScanning([],true);
	}
});
```

On my macbook heap usage will steadily rise at a rate of around 0.2 MB/min, and will never go down.

I think this is might be the fix: https://github.com/noble/noble/pull/722/files

**Comment by rzr** [comment]
Feel free to review upstream or rebase on @abandonware branch

**Comment by kevinresol** [comment]
Sorry, I just ran this code for a longer time and noticed that GC will actually sweep once a while and memory usage is steady over a longer period. Closing for now.

**Comment by airdrummingfool** [comment]
I just ran a 1 month memory test using a slight modification of the code above, and I'm seeing a consistent 1.6mb/day increase in usage.
![image](https://user-images.githubusercontent.com/631249/102048594-0f44d700-3da5-11eb-9424-64d28ff16ce2.png)

This was on an RPi 4B running on Node `14.15.0`. Over the course of the month, Noble called the `discover` event handler roughly 89 million times (there's about 20 constantly-advertising BLE devices within range).

@kevinresol how long did you run your test for? Would you consider re-opening this issue?

For the record, I don't think 600mb/**year** of memory bloat is in any way a crisis.
