### ISSUE TITLE
Make bindings available in TypeScript via typedefs

### ISSUE THREAD

**Issue by zilluss** [abandonware/noble#114]
Currently bindings can't be accessed in TypeScript because it's not provided by the typedefs. This can be fixed by adding the following line to the typedefs.
`export var _bindings: any;`

The user can then cast and supply their own typedefs for the corresponding binding.

**Comment by rzr** [comment]
please submit patches and review

https://github.com/abandonware/noble/pull/112

**Comment by tony-gutierrez** [comment]
This was merged. Close issue?

**Comment by rzr** [comment]
I can close feel free to open a new PR to release a version
