### ISSUE TITLE
Travis builds have started to break for me

### ISSUE THREAD

**Issue by AlCalzone** [abandonware/noble#13]
See logs:

https://travis-ci.org/AlCalzone/ioBroker.ble/builds/522936778?utm_source=github_status&utm_medium=notification

OSX is failing during compilation on Node 6, 8 and 10.
Windows is failing on Node 6, but that seems to be related to the msbuild version.

Any idea whats going on or if this is even the fault of this library?

**Comment by rzr** [comment]
make: g++-4.9: No such file or directory

**Comment by AlCalzone** [comment]
Hmm. I assume travis must have changed their images then. It used to work in the previous build.

**Comment by AlCalzone** [comment]
Sorry for bothering you - this seems to be entirely travis-related.

**Comment by rzr** [comment]
Eventually cross link to travis related issue if it's reported.

**Comment by AlCalzone** [comment]
I "fixed" it by not specifying the compiler version on OSX and dropping Node 6 on Windows from the test matrix. Did not investigate further.
