### ISSUE TITLE
Unable to connect ble devices on MAC 10.15 (Catalina)

### ISSUE THREAD

**Issue by yusheng-jia** [abandonware/noble#139]
It can discover the ble sensors, but unable to connect the ble sensors 
`peripheral.connect( function(error)
{
...
}
`
No output on the callback function.

Node version is: v8.9.4
Npm version is: v5.6.0

**Comment by rubengarciaalba** [comment]
Hi @yusheng-jia, did you find the solution for that?

I'm trying to run the quick start example on MacOS Catalina 10.15 but nothing happens after calling "startScanningAsync" function.

Node version is: 8.9.0
Npm version is: 5.5.1

**Comment by yusheng-jia** [comment]
> Hi @yusheng-jia, did you find the solution for that?
> 
> I'm trying to run the quick start example on MacOS Catalina 10.15 but nothing happens after calling "startScanningAsync" function.
> 
> Node version is: 8.9.0
> Npm version is: 5.5.1

Hi I have fixed it on firmware side.()

**Comment by yusheng-jia** [comment]
It maybe the issue of macOS . Please see https://github.com/xsens/xsens_dot_server/issues/16 .
