### ISSUE TITLE
Wrong repo identified in package.json

### ISSUE THREAD

**Issue by marksyzm** [abandonware/noble#14]
https://github.com/abandonware/noble/blob/7a99142e356279579b4efcc71bfd6351315e35dc/package.json#L13
It still points to sandeepmistry's repo. I can pick this one up if you want?

**Comment by rzr** [comment]
Sure please send PR I will release to npm then

**Comment by marksyzm** [comment]
https://github.com/abandonware/noble/pull/17

**Comment by rzr** [comment]
Looks it's fixed:
https://github.com/abandonware/noble/blob/master/package.json#L13

Maybe you can also npm badges too

BTW I noticed that:
https://www.npmjs.com/package/@abandonware/noble
is about 1,591 weekly downloads

while 1,069 for:
https://www.npmjs.com/package/noble
