### ISSUE TITLE
Thank you for this fix

### ISSUE THREAD

**Issue by LukasBombach** [abandonware/noble#16]
Just came here to say thank you so much for this fix of noble! It works perfectly!

Why always complain? Why not compliment in  a GitHub issue!

Cheers ✌️

**Comment by rzr** [comment]
you're welcome, maybe it will help that you report that in upstream too :)

Relate-to: https://github.com/abandonware/noble/issues/2

**Comment by LukasBombach** [comment]
Yeah I already did that in another ticket

**Comment by rzr** [comment]
ok good, maybe it would also help to review open patches at
https://github.com/noble/noble/pulls
if some are fine, we can apply them in the forked version
would that help too ?

**Comment by herrjemand** [comment]
YES! THANK YOU @rzr! You are a an amazing person!
