### ISSUE TITLE
Installing Noble on Alpine Linux - Dependencies

### ISSUE THREAD

**Issue by carlosanunes** [abandonware/noble#170]
The instructions do not specify how to install the library in Alpine, that is the required dependencies or equivalent ones for the libraries defined for other linux distributions.

**Comment by rzr** [comment]
isnt alpine supporting npm or yarn ?

**Comment by carlosanunes** [comment]
My questions is on the dependencies. Alpine Linux uses apk ( https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management ).

**Comment by carlosanunes** [comment]
For Alpine I found bluez, libudev-**zero** and libudev-**zero**-dev ( to replace libudev ), but no bluetooth library ( is this an actual requirement ). Is this enough for an actual working state ?

**Comment by carlosanunes** [comment]
Managed to install without errors, just warning but now experiencing same issue as #152

**Comment by carlosanunes** [comment]
Found that installing bluez, libudev-zero and libudev-zero-dev packages are enough to met Noble dependencies in Alpine.

Cheers.
