### ISSUE TITLE
Is bluetooth 5.0 supported?

### ISSUE THREAD

**Issue by DamyHao** [abandonware/noble#200]
I need to use features like Long Range Transport. Thanks in advance

**Comment by hmake98** [comment]
@DamyHao just checking again for the update if Bluetooth version 5 is supported or will be available in near future.

**Comment by kele6ra** [comment]
> I need to use features like Long Range Transport. Thanks in advance

Hello, can I ask you, what did you meant about Long Range Transport? Did you want to get legacy advertising and extended advertising messages with all PHYs (1M, 2M and Coded)?
