### ISSUE TITLE
How to install it on Synology NAS

### ISSUE THREAD

**Issue by Svision** [abandonware/noble#209]
There is no apt-get for DSM

**Comment by rzr** [comment]
Is there npm or chroot ?

what is DSM ?

**Comment by Svision** [comment]
> Is there npm or chroot ?
> 
> 
> 
> what is DSM ? 

There is npm and cheroot in the terminal.

DSM is the Synology system.

**Comment by rzr** [comment]
well it could be packaged for debian please file an RFS at debian and let us know

**Comment by chrisgruggen** [comment]
Was there any update on this? Any more support for Synology DSM?
