### ISSUE TITLE
Can not subscribe to characteristic from Raspberry Pi 4.

### ISSUE THREAD

**Issue by hkayann** [abandonware/noble#214]
I can subscribe to characteristic via Generic BLE app, but can't subscribe from Raspberry Pi via Noble.js. It does not generate any errors as well.

**Comment by hkayann** [comment]
When I further debug, I am getting this message on Raspberry Pi 4 `Error: Attribute Not Found (0x0a)`, when I try to subscribe.

**Comment by sabaatworld** [comment]
I'm also facing this issue

**Comment by hkayann** [comment]
I formatted Raspberry Pi 4 several times, suddenly it worked. BlueZ is very unstable.
