### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by Ravaniss** [abandonware/noble#24]
Hello everyone ! :)

I was on a big problem with noble since i found this one and make noble working (only the stateChange event) and thank you for that... It was a good start.

I was on the impossibility to get my devices with the discover event... Don't tell me why, no errors, just nothing appear on the terminal...

Just because i didn't read the entire doc...

Someone teach me than, it's useless to continue reading if something doesn't work or something you don't understand... It's true.

Well, then, do you know how i solve my problem ?

I solve my problem with this command line ... Who is at the bottom of this documentation...
`sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`

Now when i execute my code, he's going on my discover event and i finally get my devices...

Why the hell `Running on Linux` section is at the bottom of the documentation ?

I hope i'm not alone to do something like that. :) And i hope so, but please, can you put the `Running on Linux` section at the top inside Prerequisites or Notes maybe ?

Maybe that will help others...

**Comment by rzr** [comment]
Patches welcome here or in @abandonware fork
