### ISSUE TITLE
Direct abort when running quick start example from Mac M1

### ISSUE THREAD

**Issue by StephaneJuban** [abandonware/noble#255]
Hi,

I am trying to transfert my local server from my old Macbook Intel to my new one running on macOS Monterey and M1 chip.

I am using the same version of node (16.0.0) on both machine.

But on my M1, as soon as I start the quick start example, the server crash.
```
node app.js
[1]    44669 abort      node app.js
```

The crash happens as soon as I reach `noble.on('stateChange', async (state) => { ... });`

Any idea why ?

---

- node v16.0.0
- Macbook M1 Pro
- macOS Monterey 12.3.1

**Comment by si-stratisiot** [comment]
I'm getting the same error with macOS 12.4 and Intel chip

**Comment by squidgetx** [comment]
I was able to solve this on 12.3.1 Intel mac by adding terminal to allowed bluetooth apps using these instructions: https://github.com/abandonware/noble#os-x

**Comment by StephaneJuban** [comment]
> I was able to solve this on 12.3.1 Intel mac by adding terminal to allowed bluetooth apps using these instructions: https://github.com/abandonware/noble#os-x

Thanks this worked !
