### ISSUE TITLE
Wrong node-bluetooth-hci-socket version

### ISSUE THREAD

**Issue by vwang4536** [abandonware/noble#325]
In the package.json optional dependencies:  "@abandonware/bluetooth-hci-socket": "^0.5.3-11" is expected however the latest version that is currently out for it is ^0.5.3-10. Can we get a quick update to change the version in package.json to 0.5.3-10?

**Comment by lpgera** [comment]
@vwang4536 Why did you close the issue? I'm having the same problem and I can't find a solution, so I'd be curious to know yours.

**Comment by vwang4536** [comment]
> @vwang4536 Why did you close the issue? I'm having the same problem and I can't find a solution, so I'd be curious to know yours.

I'm just using 1.9.2-23 for now since the version bump for bluetooth-hci-socket was pretty recent. Can also create a PR to revert the version update for bluetooth-hci-socket back to 0.5.3-10

**Comment by lpgera** [comment]
If there's no solution then could you reopen the issue please?
